juan-section-11 updated section 11 and some comments in other sections
JuanDelahozMiranda/cypressTraining-update pull request #5
Opened 2023-03-06 21:43 UTC by JuanDelahozMiranda

2023-03-07 15:17 UTC, diegobonilla86 commented on README.md
> +    private shoppingbtn: string
Good practice to name variables:

private shoppingBtn: string

2023-03-07 16:16 UTC, diegobonilla86 requested changes
Please rename variables and methods according to the comments

2023-03-07 16:16 UTC, diegobonilla86 commented on README.md
> +    private containeritems: string;
private containerItems: string;

2023-03-07 16:16 UTC, diegobonilla86 commented on README.md
> +        this.shoppingbtn = ".shopping_cart_link";
this.shoppingBtn = ".shopping_cart_link";

2023-03-07 16:16 UTC, diegobonilla86 commented on README.md
> +        this.containeritems = ":nth-child(2) > :nth-child(1) > #inventory_container";
this.containerItems = ":nth-child(2) > :nth-child(1) > #inventory_container";

2023-03-07 16:16 UTC, diegobonilla86 commented on README.md
> +        this.itemBackpack_AddBtn = "[data-test=\"add-to-cart-sauce-labs-backpack\"]";
this.itemBackPack_AddBtn = "[data-test=\"add-to-cart-sauce-labs-backpack\"]";

2023-03-07 16:16 UTC, diegobonilla86 commented on README.md
> +    public goToShoppingcar():void{
public goToShoppingCart():void{

2023-03-07 16:16 UTC, diegobonilla86 commented on README.md
> +        cy.get(this.shoppingbtn).click();
cy.get(this.shoppingBtn).click();

2023-03-07 17:13 UTC, luisdanielvcord commented on README.md
> +    public goToShoppingcar():void{
There's a small typo on the function name, it should be "goToShoppingCart()" with a capital "C" and a "t" at the end

2023-03-07 17:13 UTC, luisdanielvcord commented on README.md
> +        this.priceItem = ":nth-child(1) > .inventory_item_description > .pricebar > .inventory_item_price";
Since we improved the selectors in section 10, Shouldn't we provide ideal selectors for this example?

2023-03-07 17:13 UTC, luisdanielvcord commented on README.md
> -     }
By removing the validateItemsNames method we are reducing code complexity, Is this expected?

2023-03-07 17:16 UTC, JuanDelahozMiranda commented on README.md
> -     }
in this case the method was based in the before page, so is updated

2023-03-07 17:17 UTC, JuanDelahozMiranda commented on README.md
> +    public goToShoppingcar():void{
ok

2023-03-07 20:28 UTC, luisdanielvcord approved these changes

2023-03-08 02:31 UTC, diegobonilla86 approved these changes

2023-03-08 02:32 UTC, merged

2023-03-08 13:46 UTC, davidmoralesv commented on README.md
> +   - Recomendamos usar [nvm](https://github.com/nvm-sh/nvm) como manejador de versiones (Opcional).
Esto confunde tanto que una persona que comienza el workshop, va a instalar nvm para luego darse cuenta que no lo va a necesitar. Además que está fuera de lugar porque todo el tiempo se usa npm.